### ISSUE TITLE
BitSnoop icon

### ISSUE THREAD

**Issue by Greenbaburu** [mancuniancol/script.quasar.bitsnoop-mc#1]
preview
![bitsnoop](https://cloud.githubusercontent.com/assets/8045152/13126256/0bd8793e-d5ca-11e5-9eb8-db191a76967e.jpg)

PNG
![bitsnoop](https://cloud.githubusercontent.com/assets/8045152/13126266/1126811a-d5ca-11e5-9945-21c9f9785335.png)

**Comment by mancuniancol** [comment]
Great job. I've updated all the icons that you've already sent me. They look gorgeous :)
